baseURL = ""
enableEmoji = true
languageCode = "en-us"
title = "rhymes.dev"
theme = "hugo-coder"
pygmentsUseClasses = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = "base16-snazzy"

# Hugo Coder Theme
[params]
  author = "rhymes"
  info = "Software developer"
  description = "rhymes personal site"
  keywords = "rhymes,software,developer,web"

  avatarURL = "images/avatar.jpg"
  favicon_32 = "images/favicon_32.png"
  favicon_16 = "images/favicon_16.png"
  touchIcon = "images/apple-touch-icon.png"
  hideFooter = true
  colorScheme = "auto"
  enableTwemoji = false

  customCSS = ["css/custom.css"]

[[params.social]]
  name = "GitHub"
  icon = "fa fa-github fa-2x"
  url = "https://github.com/rhymes"
  [[params.social]]
    name = "DEV"
    icon = "fa fa-brands fa-dev fa-2x"
    url = "https://dev.to/rhymes"
[[params.social]]
  name = "Twitter/X"
  icon = "fa fa-x fa-2x"
  url = "https://twitter.com/rhymes_"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-brands fa-mastodon fa-2x"
  url = "https://hachyderm.io/@rhymes"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  url = "mailto:me@rhymes.dev"

[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Work experience"
  weight = 2
  url = "work/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
